// AUTO-GENERATED by `npm run gen:sprites` — do not edit by hand.
// Regenerate: npm run gen:sprites
package com.rs3buddy;

/** Sprite names as autocomplete-able constants (e.g. SpriteNames.ALL_CHAT)
 *  plus the full SPRITE_NAMES array for iteration. */
public final class SpriteNames {
    private SpriteNames() {}

    public static final String ABILITY_ABILITY_WAIT_7 = "ability:ability_wait_7";
    public static final String ABILITY_ANTICIPATION = "ability:anticipation";
    public static final String ABILITY_ASPHYXIATE = "ability:asphyxiate";
    public static final String ABILITY_ATTACK_ABILITIES = "ability:attack_abilities";
    public static final String ABILITY_BACKHAND = "ability:backhand";
    public static final String ABILITY_BARGE = "ability:barge";
    public static final String ABILITY_BARRICADE = "ability:barricade";
    public static final String ABILITY_BASH = "ability:bash";
    public static final String ABILITY_BLOAT = "ability:bloat";
    public static final String ABILITY_BLOOD_SIPHON = "ability:blood_siphon";
    public static final String ABILITY_BONE_SHEILD_INACTIVE = "ability:bone_sheild_inactive";
    public static final String ABILITY_BONE_SHIELD_ACTIVE = "ability:bone_shield_active";
    public static final String ABILITY_CAST_FAMILIAR_SPECIAL_ABILITY = "ability:cast_familiar_special_ability";
    public static final String ABILITY_CEASE = "ability:cease";
    public static final String ABILITY_COMBUST = "ability:combust";
    public static final String ABILITY_COMMAND_SKELETON_WARRIOR = "ability:command_skeleton_warrior";
    public static final String ABILITY_COMMAND_VENGEFUL_GHOST = "ability:command_vengeful_ghost";
    public static final String ABILITY_CONCETRATED_BLAST = "ability:concetrated_blast";
    public static final String ABILITY_CONJURE_GUARDIAN_PHANTOM = "ability:conjure_guardian_phantom";
    public static final String ABILITY_CONJURE_PHANTOM_GUARDIAN = "ability:conjure_phantom_guardian";
    public static final String ABILITY_CONJURE_PUTRID_ZOMBIE = "ability:conjure_putrid_zombie";
    public static final String ABILITY_CONJURE_SKELETON_WARRIOR = "ability:conjure_skeleton_warrior";
    public static final String ABILITY_CONJURE_UNDEAD_ARMY = "ability:conjure_undead_army";
    public static final String ABILITY_CONJURE_VENGEFUL_GHOST = "ability:conjure_vengeful_ghost";
    public static final String ABILITY_CORRUPTION_BLAST = "ability:corruption_blast";
    public static final String ABILITY_DARKNESS = "ability:darkness";
    public static final String ABILITY_DEATH_SKULLS = "ability:death_skulls";
    public static final String ABILITY_DEBILITATE = "ability:debilitate";
    public static final String ABILITY_DEFLECT_SUMMONING = "ability:deflect_summoning";
    public static final String ABILITY_DEVOTION = "ability:devotion";
    public static final String ABILITY_DIVE = "ability:dive";
    public static final String ABILITY_EAT_FOOD = "ability:eat_food";
    public static final String ABILITY_ESCAPE = "ability:escape";
    public static final String ABILITY_ESSENCE_OF_FINALITY = "ability:essence_of_finality";
    public static final String ABILITY_FINGER_OF_DEATH = "ability:finger_of_death";
    public static final String ABILITY_FLURRY = "ability:flurry";
    public static final String ABILITY_FREEDOM = "ability:freedom";
    public static final String ABILITY_GALESHOT = "ability:galeshot";
    public static final String ABILITY_GREATER_BONE_SHIELD_ACTIVE = "ability:greater_bone_shield_active";
    public static final String ABILITY_HEALTH_BAR_GREEN = "ability:health_bar_green";
    public static final String ABILITY_ICE_ASYLUM = "ability:ice_asylum";
    public static final String ABILITY_ICE_BARRAGE = "ability:ice_barrage";
    public static final String ABILITY_ID11J5AWR = "ability:id11j5awr";
    public static final String ABILITY_ID156QQ6P = "ability:id156qq6p";
    public static final String ABILITY_ID1DFKYL4 = "ability:id1dfkyl4";
    public static final String ABILITY_ID1G090O2 = "ability:id1g090o2";
    public static final String ABILITY_ID1NGWN7R = "ability:id1ngwn7r";
    public static final String ABILITY_ID1NL6PA4 = "ability:id1nl6pa4";
    public static final String ABILITY_IDABRV9T = "ability:idabrv9t";
    public static final String ABILITY_IDKGUJT = "ability:idkgujt";
    public static final String ABILITY_IDXAIINN = "ability:idxaiinn";
    public static final String ABILITY_IDZD075O = "ability:idzd075o";
    public static final String ABILITY_IMBUE__SHADOWS = "ability:imbue:_shadows";
    public static final String ABILITY_IMMORTALITY = "ability:immortality";
    public static final String ABILITY_INCITE = "ability:incite";
    public static final String ABILITY_INVOKE_DEATH = "ability:invoke_death";
    public static final String ABILITY_LIFE_TRANSFER = "ability:life_transfer";
    public static final String ABILITY_LIVING_DEATH = "ability:living_death";
    public static final String ABILITY_MAGIC = "ability:magic";
    public static final String ABILITY_MAGIC_SPIN_FLAX = "ability:magic:spin_flax";
    public static final String ABILITY_NECROMANCY = "ability:necromancy";
    public static final String ABILITY_NECROMANCY_ABILITIES = "ability:necromancy_abilities";
    public static final String ABILITY_OMNIPOWER = "ability:omnipower";
    public static final String ABILITY_OVERPOWER = "ability:overpower";
    public static final String ABILITY_PREPARATION = "ability:preparation";
    public static final String ABILITY_PROVOKE = "ability:provoke";
    public static final String ABILITY_PUNISH = "ability:punish";
    public static final String ABILITY_RANGED = "ability:ranged";
    public static final String ABILITY_RANGED_ABILITIES = "ability:ranged_abilities";
    public static final String ABILITY_REFLECT = "ability:reflect";
    public static final String ABILITY_REGENERATE = "ability:regenerate";
    public static final String ABILITY_REJUVENATE = "ability:rejuvenate";
    public static final String ABILITY_REND = "ability:rend";
    public static final String ABILITY_REVENGE = "ability:revenge";
    public static final String ABILITY_SACRAFICE = "ability:sacrafice";
    public static final String ABILITY_SAP_DEFENCE = "ability:sap_defence";
    public static final String ABILITY_SAP_MAGIC_STRENGTH = "ability:sap_magic_strength";
    public static final String ABILITY_SIPHON = "ability:siphon";
    public static final String ABILITY_SONIC_WAVE = "ability:sonic_wave";
    public static final String ABILITY_SOUL_SAP = "ability:soul_sap";
    public static final String ABILITY_SPECIAL_ATTACK = "ability:special_attack";
    public static final String ABILITY_SPECTRAL_SCYTHE = "ability:spectral_scythe";
    public static final String ABILITY_SPLIT_SOUL = "ability:split_soul";
    public static final String ABILITY_SURGE = "ability:surge";
    public static final String ABILITY_THREADS_OF_FATE = "ability:threads_of_fate";
    public static final String ABILITY_TOUCH_OF_DEATH = "ability:touch_of_death";
    public static final String ABILITY_TRANSFIGURE = "ability:transfigure";
    public static final String ABILITY_TSUNAMI = "ability:tsunami";
    public static final String ABILITY_VOLLEY_OF_SOULS = "ability:volley_of_souls";
    public static final String BAR_ADRENALINE_BAR = "bar:adrenaline_bar";
    public static final String BAR_ADRENALINE_BAR_BACKGROUND = "bar:adrenaline_bar_background";
    public static final String BAR_ADRENALINE_BAR_FULL_BACKGROUND = "bar:adrenaline_bar_full_background";
    public static final String BAR_ADRENALINE_BAR_OVERCHARGE = "bar:adrenaline_bar_overcharge";
    public static final String BAR_BLUE_BACKGROUND_BAR = "bar:blue_background_bar";
    public static final String BAR_CONJURE_BAR_BACKGROUND = "bar:conjure_bar_background";
    public static final String BAR_GREEN_BAR = "bar:green_bar";
    public static final String BAR_SKILLING_BAR_BEGINNING = "bar:skilling_bar_beginning";
    public static final String BAR_SKILLING_BAR_END = "bar:skilling_bar_end";
    public static final String BAR_SKILLING_BAR_MIDDLE = "bar:skilling_bar_middle";
    public static final String BAR_YELLOW_FRONTGROUND_BAR = "bar:yellow_frontground_bar";
    public static final String BUFF_BLOAT = "buff:bloat";
    public static final String BUFF_BONE_SHIELD = "buff:bone_shield";
    public static final String BUFF_BUFF_BOX = "buff:buff_box";
    public static final String BUFF_COMMAND_PUTRID_ZOMBIE = "buff:command_putrid_zombie";
    public static final String BUFF_DEVOTION = "buff:devotion";
    public static final String BUFF_FREEDOM = "buff:freedom";
    public static final String BUFF_NECROSIS = "buff:necrosis";
    public static final String BUFF_PUTRID_ZOMBIE = "buff:putrid_zombie";
    public static final String BUFF_RESIDUAL_SOUL = "buff:residual_soul";
    public static final String BUFF_SKELETON_WARRIOR = "buff:skeleton_warrior";
    public static final String BUFF_VENGEFUL_GHOST = "buff:vengeful_ghost";
    public static final String CHAT_ID1A0B3GF = "chat:id1a0b3gf";
    public static final String CHAT_ID1QBJ1GL = "chat:id1qbj1gl";
    public static final String CHAT_IDIPYDXW = "chat:idipydxw";
    public static final String CHATBOX_ALL_CHAT = "chatbox:all_chat";
    public static final String CHATBOX_CHAT_COG = "chatbox:chat_cog";
    public static final String CHATBOX_CHAT_FILTER = "chatbox:chat_filter";
    public static final String CHATBOX_CHATBOX_COG = "chatbox:chatbox_cog";
    public static final String CHATBOX_CLAN_CHAT = "chatbox:clan_chat";
    public static final String CHATBOX_CLAN_CHAT_LIST = "chatbox:clan_chat_list";
    public static final String CHATBOX_FRIENDS_CHAT = "chatbox:friends_chat";
    public static final String CHATBOX_FRIENDS_CHAT_LIST = "chatbox:friends_chat_list";
    public static final String CHATBOX_FRIENDS_LIST = "chatbox:friends_list";
    public static final String CHATBOX_GROUP_CHAT = "chatbox:group_chat";
    public static final String CHATBOX_GROUP_CHAT_LIST = "chatbox:group_chat_list";
    public static final String CHATBOX_GUEST_CLAN_CHAT = "chatbox:guest_clan_chat";
    public static final String CHATBOX_ID1EH8QO7 = "chatbox:id1eh8qo7";
    public static final String CHATBOX_ID1F6HC4U = "chatbox:id1f6hc4u";
    public static final String CHATBOX_IDBIHU5W = "chatbox:idbihu5w";
    public static final String CHATBOX_IDFBT6RN = "chatbox:idfbt6rn";
    public static final String CHATBOX_IRONMAN = "chatbox:ironman";
    public static final String CHATBOX_NEWS_ICON = "chatbox:news_icon";
    public static final String CHATBOX_QUICK_CHAT = "chatbox:quick_chat";
    public static final String ENEMY_DEBUFF_BLOAT = "enemy_debuff:bloat";
    public static final String ENEMY_DEBUFF_DEFENSE_MODIFIED = "enemy_debuff:defense_modified";
    public static final String FAMILIAR_ORB = "familiar:orb";
    public static final String ID11NQECK = "id11nqeck";
    public static final String ID198MXHV = "id198mxhv";
    public static final String ID1H4RO9I = "id1h4ro9i";
    public static final String ID1IYQJ6N = "id1iyqj6n";
    public static final String ID1KFZFDV = "id1kfzfdv";
    public static final String ID1XVG1T0 = "id1xvg1t0";
    public static final String ID6SNER1 = "id6sner1";
    public static final String ID7DUESD = "id7duesd";
    public static final String IDB4OO8Y = "idb4oo8y";
    public static final String IDL9SSJY = "idl9ssjy";
    public static final String IDMVCM2U = "idmvcm2u";
    public static final String IDPMGS62 = "idpmgs62";
    public static final String IDRLDWUJ = "idrldwuj";
    public static final String INTERFACE_ABILITY_ACTIVATION_TIMER = "interface:ability_activation_timer";
    public static final String INTERFACE_ABILITY_WAIT_1 = "interface:ability_wait_1";
    public static final String INTERFACE_ABILITY_WAIT_2 = "interface:ability_wait_2";
    public static final String INTERFACE_ABILITY_WAIT_3 = "interface:ability_wait_3";
    public static final String INTERFACE_ABILITY_WAIT_5 = "interface:ability_wait_5";
    public static final String INTERFACE_ABILITY_WAIT_6 = "interface:ability_wait_6";
    public static final String INTERFACE_ADRENALINE_BAR = "interface:adrenaline_bar";
    public static final String INTERFACE_ALL_COMBAT = "interface:all_combat";
    public static final String INTERFACE_AUTO_RETALIATE_ON = "interface:auto_retaliate_on";
    public static final String INTERFACE_BUFF_BAR_3D = "interface:buff_bar_3d";
    public static final String INTERFACE_CALENDAR = "interface:calendar";
    public static final String INTERFACE_COIN_POUCH = "interface:coin_pouch";
    public static final String INTERFACE_CONJURE_BAR = "interface:conjure_bar";
    public static final String INTERFACE_CONJURE_BAR_1 = "interface:conjure_bar_1";
    public static final String INTERFACE_CONJURE_BAR_2 = "interface:conjure_bar_2";
    public static final String INTERFACE_CONJURE_HITSPLAT_END = "interface:conjure_hitsplat_end";
    public static final String INTERFACE_CONJURE_SPLAT_3 = "interface:conjure_splat_3";
    public static final String INTERFACE_CONSTITUTION_ICON = "interface:constitution_icon";
    public static final String INTERFACE_CURRENCY_POUCH = "interface:currency_pouch";
    public static final String INTERFACE_DEFENCE_ABILTIES = "interface:defence_abilties";
    public static final String INTERFACE_DISASSEMBLE = "interface:disassemble";
    public static final String INTERFACE_EMOTES = "interface:emotes";
    public static final String INTERFACE_EMPTY_BAR_3D = "interface:empty_bar_3d";
    public static final String INTERFACE_EMPTY_BAR_OTHER_3D = "interface:empty_bar_other_3d";
    public static final String INTERFACE_FAMILIAR_BAR = "interface:familiar_bar";
    public static final String INTERFACE_FAMILIAR_OPTIONS = "interface:familiar_options";
    public static final String INTERFACE_FILTER = "interface:filter";
    public static final String INTERFACE_HEALTH_BAR_GREEN = "interface:health_bar_green";
    public static final String INTERFACE_HEALTH_LOSS_BAR = "interface:health_loss_bar";
    public static final String INTERFACE_HITPOINTS_BAR = "interface:hitpoints_bar";
    public static final String INTERFACE_HITPOINTS_ICON = "interface:hitpoints_icon";
    public static final String INTERFACE_ID10REWJF = "interface:id10rewjf";
    public static final String INTERFACE_ID11GPYOX = "interface:id11gpyox";
    public static final String INTERFACE_ID1230YAL = "interface:id1230yal";
    public static final String INTERFACE_ID12CTFZY = "interface:id12ctfzy";
    public static final String INTERFACE_ID12X6O2F = "interface:id12x6o2f";
    public static final String INTERFACE_ID1308N00 = "interface:id1308n00";
    public static final String INTERFACE_ID1321HI9 = "interface:id1321hi9";
    public static final String INTERFACE_ID13G1HD5 = "interface:id13g1hd5";
    public static final String INTERFACE_ID13I9WB1 = "interface:id13i9wb1";
    public static final String INTERFACE_ID14R9347 = "interface:id14r9347";
    public static final String INTERFACE_ID158NE25 = "interface:id158ne25";
    public static final String INTERFACE_ID15CZ86A = "interface:id15cz86a";
    public static final String INTERFACE_ID15HC6RT = "interface:id15hc6rt";
    public static final String INTERFACE_ID15OJNAQ = "interface:id15ojnaq";
    public static final String INTERFACE_ID16VJYN0 = "interface:id16vjyn0";
    public static final String INTERFACE_ID18A2OL1 = "interface:id18a2ol1";
    public static final String INTERFACE_ID19YHJWT = "interface:id19yhjwt";
    public static final String INTERFACE_ID1ALM7GB = "interface:id1alm7gb";
    public static final String INTERFACE_ID1BNEK5Q = "interface:id1bnek5q";
    public static final String INTERFACE_ID1CT714F = "interface:id1ct714f";
    public static final String INTERFACE_ID1D0ROVO = "interface:id1d0rovo";
    public static final String INTERFACE_ID1D18IIL = "interface:id1d18iil";
    public static final String INTERFACE_ID1D5PZSC = "interface:id1d5pzsc";
    public static final String INTERFACE_ID1D9B31N = "interface:id1d9b31n";
    public static final String INTERFACE_ID1DEH90W = "interface:id1deh90w";
    public static final String INTERFACE_ID1DEUWKI = "interface:id1deuwki";
    public static final String INTERFACE_ID1EI5A4P = "interface:id1ei5a4p";
    public static final String INTERFACE_ID1F485X0 = "interface:id1f485x0";
    public static final String INTERFACE_ID1FEPFX = "interface:id1fepfx";
    public static final String INTERFACE_ID1G090O2 = "interface:id1g090o2";
    public static final String INTERFACE_ID1G3DAZP = "interface:id1g3dazp";
    public static final String INTERFACE_ID1GFHRRS = "interface:id1gfhrrs";
    public static final String INTERFACE_ID1GFT0ZE = "interface:id1gft0ze";
    public static final String INTERFACE_ID1GW501J = "interface:id1gw501j";
    public static final String INTERFACE_ID1HEPSZ9 = "interface:id1hepsz9";
    public static final String INTERFACE_ID1HFEH0M = "interface:id1hfeh0m";
    public static final String INTERFACE_ID1HIZOPR = "interface:id1hizopr";
    public static final String INTERFACE_ID1HT5UV9 = "interface:id1ht5uv9";
    public static final String INTERFACE_ID1HUSF0R = "interface:id1husf0r";
    public static final String INTERFACE_ID1JGTSF6 = "interface:id1jgtsf6";
    public static final String INTERFACE_ID1JR0X5W = "interface:id1jr0x5w";
    public static final String INTERFACE_ID1K1PTAL = "interface:id1k1ptal";
    public static final String INTERFACE_ID1K5ZSKO = "interface:id1k5zsko";
    public static final String INTERFACE_ID1K9CUOO = "interface:id1k9cuoo";
    public static final String INTERFACE_ID1K9I5LF = "interface:id1k9i5lf";
    public static final String INTERFACE_ID1KB1JT7 = "interface:id1kb1jt7";
    public static final String INTERFACE_ID1L65XAO = "interface:id1l65xao";
    public static final String INTERFACE_ID1LBWRIV = "interface:id1lbwriv";
    public static final String INTERFACE_ID1LCTL0I = "interface:id1lctl0i";
    public static final String INTERFACE_ID1LVIOK2 = "interface:id1lviok2";
    public static final String INTERFACE_ID1MRE2TD = "interface:id1mre2td";
    public static final String INTERFACE_ID1N009SA = "interface:id1n009sa";
    public static final String INTERFACE_ID1NFYGXU = "interface:id1nfygxu";
    public static final String INTERFACE_ID1NLDB00 = "interface:id1nldb00";
    public static final String INTERFACE_ID1NPMZHM = "interface:id1npmzhm";
    public static final String INTERFACE_ID1NX0R7R = "interface:id1nx0r7r";
    public static final String INTERFACE_ID1O7KBF7 = "interface:id1o7kbf7";
    public static final String INTERFACE_ID1OWHY7U = "interface:id1owhy7u";
    public static final String INTERFACE_ID1P66E6X = "interface:id1p66e6x";
    public static final String INTERFACE_ID1P6QMMR = "interface:id1p6qmmr";
    public static final String INTERFACE_ID1QFFSDZ = "interface:id1qffsdz";
    public static final String INTERFACE_ID1QZBHIZ = "interface:id1qzbhiz";
    public static final String INTERFACE_ID1RSC57A = "interface:id1rsc57a";
    public static final String INTERFACE_ID1RTGTM = "interface:id1rtgtm";
    public static final String INTERFACE_ID1S0YBMW = "interface:id1s0ybmw";
    public static final String INTERFACE_ID1SEB3GP = "interface:id1seb3gp";
    public static final String INTERFACE_ID1SSW4GZ = "interface:id1ssw4gz";
    public static final String INTERFACE_ID1SY954C = "interface:id1sy954c";
    public static final String INTERFACE_ID1T383SC = "interface:id1t383sc";
    public static final String INTERFACE_ID1U40ZWT = "interface:id1u40zwt";
    public static final String INTERFACE_ID1VCF9YQ = "interface:id1vcf9yq";
    public static final String INTERFACE_ID1W7MSOD = "interface:id1w7msod";
    public static final String INTERFACE_ID1WPFHLH = "interface:id1wpfhlh";
    public static final String INTERFACE_ID1WRJ9F4 = "interface:id1wrj9f4";
    public static final String INTERFACE_ID1WRVPWW = "interface:id1wrvpww";
    public static final String INTERFACE_ID1WTU07L = "interface:id1wtu07l";
    public static final String INTERFACE_ID1WY1B4G = "interface:id1wy1b4g";
    public static final String INTERFACE_ID1YGQK80 = "interface:id1ygqk80";
    public static final String INTERFACE_ID1YNPRTT = "interface:id1ynprtt";
    public static final String INTERFACE_ID1YRUF8N = "interface:id1yruf8n";
    public static final String INTERFACE_ID1YZIV8A = "interface:id1yziv8a";
    public static final String INTERFACE_ID268YB4 = "interface:id268yb4";
    public static final String INTERFACE_ID2SC66L = "interface:id2sc66l";
    public static final String INTERFACE_ID3FMEHD = "interface:id3fmehd";
    public static final String INTERFACE_ID3IMX4R = "interface:id3imx4r";
    public static final String INTERFACE_ID4EA0RJ = "interface:id4ea0rj";
    public static final String INTERFACE_ID58543 = "interface:id58543";
    public static final String INTERFACE_ID5OT662 = "interface:id5ot662";
    public static final String INTERFACE_ID5P8W63 = "interface:id5p8w63";
    public static final String INTERFACE_ID5U11G9 = "interface:id5u11g9";
    public static final String INTERFACE_ID66WXYU = "interface:id66wxyu";
    public static final String INTERFACE_ID6U306F = "interface:id6u306f";
    public static final String INTERFACE_ID70ZJ8Q = "interface:id70zj8q";
    public static final String INTERFACE_ID74IMW0 = "interface:id74imw0";
    public static final String INTERFACE_ID7JWUW1 = "interface:id7jwuw1";
    public static final String INTERFACE_ID7OICE2 = "interface:id7oice2";
    public static final String INTERFACE_ID88R93R = "interface:id88r93r";
    public static final String INTERFACE_ID91A89K = "interface:id91a89k";
    public static final String INTERFACE_ID96S93B = "interface:id96s93b";
    public static final String INTERFACE_IDBQTGUP = "interface:idbqtgup";
    public static final String INTERFACE_IDC0T1E7 = "interface:idc0t1e7";
    public static final String INTERFACE_IDDLF03X = "interface:iddlf03x";
    public static final String INTERFACE_IDE4PUME = "interface:ide4pume";
    public static final String INTERFACE_IDEB9UZZ = "interface:ideb9uzz";
    public static final String INTERFACE_IDEEQZ3V = "interface:ideeqz3v";
    public static final String INTERFACE_IDEV9LHL = "interface:idev9lhl";
    public static final String INTERFACE_IDF2JGA3 = "interface:idf2jga3";
    public static final String INTERFACE_IDGNRKTP = "interface:idgnrktp";
    public static final String INTERFACE_IDH79I3K = "interface:idh79i3k";
    public static final String INTERFACE_IDHIDNF5 = "interface:idhidnf5";
    public static final String INTERFACE_IDHQ4G5X = "interface:idhq4g5x";
    public static final String INTERFACE_IDIBKC63 = "interface:idibkc63";
    public static final String INTERFACE_IDIFKFB8 = "interface:idifkfb8";
    public static final String INTERFACE_IDII9G52 = "interface:idii9g52";
    public static final String INTERFACE_IDJS2M1E = "interface:idjs2m1e";
    public static final String INTERFACE_IDL9SH9X = "interface:idl9sh9x";
    public static final String INTERFACE_IDLM413K = "interface:idlm413k";
    public static final String INTERFACE_IDLMD6JE = "interface:idlmd6je";
    public static final String INTERFACE_IDLQW7NF = "interface:idlqw7nf";
    public static final String INTERFACE_IDLRXUUP = "interface:idlrxuup";
    public static final String INTERFACE_IDLZJ8XZ = "interface:idlzj8xz";
    public static final String INTERFACE_IDN6BCO1 = "interface:idn6bco1";
    public static final String INTERFACE_IDN9P8Q3 = "interface:idn9p8q3";
    public static final String INTERFACE_IDNQLJI5 = "interface:idnqlji5";
    public static final String INTERFACE_IDNZ172 = "interface:idnz172";
    public static final String INTERFACE_IDO07MZ7 = "interface:ido07mz7";
    public static final String INTERFACE_IDO4HAVU = "interface:ido4havu";
    public static final String INTERFACE_IDOEHP0R = "interface:idoehp0r";
    public static final String INTERFACE_IDOWUCM4 = "interface:idowucm4";
    public static final String INTERFACE_IDP2IX07 = "interface:idp2ix07";
    public static final String INTERFACE_IDP6B4UC = "interface:idp6b4uc";
    public static final String INTERFACE_IDPTXIH7 = "interface:idptxih7";
    public static final String INTERFACE_IDPXS1L1 = "interface:idpxs1l1";
    public static final String INTERFACE_IDQ2WAG = "interface:idq2wag";
    public static final String INTERFACE_IDR3IMEN = "interface:idr3imen";
    public static final String INTERFACE_IDSSMWT8 = "interface:idssmwt8";
    public static final String INTERFACE_IDT52LL5 = "interface:idt52ll5";
    public static final String INTERFACE_IDT594GJ = "interface:idt594gj";
    public static final String INTERFACE_IDTKH2M7 = "interface:idtkh2m7";
    public static final String INTERFACE_IDTPZVFK = "interface:idtpzvfk";
    public static final String INTERFACE_IDTTRSJ3 = "interface:idttrsj3";
    public static final String INTERFACE_IDU2UC0L = "interface:idu2uc0l";
    public static final String INTERFACE_IDUH1HR = "interface:iduh1hr";
    public static final String INTERFACE_IDUU2ZRS = "interface:iduu2zrs";
    public static final String INTERFACE_IDUVNCHK = "interface:iduvnchk";
    public static final String INTERFACE_IDVO4D7R = "interface:idvo4d7r";
    public static final String INTERFACE_IDW73JM1 = "interface:idw73jm1";
    public static final String INTERFACE_IDWERV2I = "interface:idwerv2i";
    public static final String INTERFACE_IDWO0ATG = "interface:idwo0atg";
    public static final String INTERFACE_IDWQ8BN3 = "interface:idwq8bn3";
    public static final String INTERFACE_IDXC84NM = "interface:idxc84nm";
    public static final String INTERFACE_IDXD3YCM = "interface:idxd3ycm";
    public static final String INTERFACE_IDYUCOYI = "interface:idyucoyi";
    public static final String INTERFACE_IDZD075O = "interface:idzd075o";
    public static final String INTERFACE_IDZLI5LZ = "interface:idzli5lz";
    public static final String INTERFACE_INVENTION_MATERIALS = "interface:invention_materials";
    public static final String INTERFACE_INVOKE_DEATH = "interface:invoke_death";
    public static final String INTERFACE_LOCK_INVENTORY = "interface:lock_inventory";
    public static final String INTERFACE_MAGIC = "interface:magic";
    public static final String INTERFACE_MAGIC_ABILITIES = "interface:magic_abilities";
    public static final String INTERFACE_MAGIC_TELEPORT_SPELLS = "interface:magic_teleport_spells";
    public static final String INTERFACE_MELEE_ABILITIES = "interface:melee_abilities";
    public static final String INTERFACE_NECROMANCY_ABILITIES = "interface:necromancy_abilities";
    public static final String INTERFACE_NECROMANCY_CONJURE_HIT_1 = "interface:necromancy_conjure_hit_1";
    public static final String INTERFACE_NECROMANCY_CONJURE_HIT_2 = "interface:necromancy_conjure_hit_2";
    public static final String INTERFACE_NECROMANCY_CONJURE_HITSPLAT_BEGINNING = "interface:necromancy_conjure_hitsplat_beginning";
    public static final String INTERFACE_NECROMANCY_HIT_1 = "interface:necromancy_hit_1";
    public static final String INTERFACE_NECROMANCY_INCANTATIONS = "interface:necromancy_incantations";
    public static final String INTERFACE_PRAYER_BAR = "interface:prayer_bar";
    public static final String INTERFACE_PRAYER_OFF = "interface:prayer_off";
    public static final String INTERFACE_PRAYERS_TAB = "interface:prayers_tab";
    public static final String INTERFACE_QUEST_FILTER = "interface:quest_filter";
    public static final String INTERFACE_QUEST_ICON_1 = "interface:quest_icon_1";
    public static final String INTERFACE_QUEST_ICON_2 = "interface:quest_icon_2";
    public static final String INTERFACE_QUICK_PRAYER = "interface:quick_prayer";
    public static final String INTERFACE_QUICK_PRAYER_4 = "interface:quick_prayer_4";
    public static final String INTERFACE_RANGED_ABILITIES = "interface:ranged_abilities";
    public static final String INTERFACE_RESIDUAL_SOULS_EMPTY = "interface:residual_souls_empty";
    public static final String INTERFACE_RESIDUAL_SOULS_FULL = "interface:residual_souls_full";
    public static final String INTERFACE_RUN_ENERGY_ON = "interface:run_energy_on";
    public static final String INTERFACE_SLAYER_ICON = "interface:slayer_icon";
    public static final String INTERFACE_SOUL_SAP = "interface:soul_sap";
    public static final String INTERFACE_STUN_IMMUNITY = "interface:stun_immunity";
    public static final String INTERFACE_TOTAL_XP = "interface:total_xp";
    public static final String INTERFACE_WEALTH_EVALUATOR = "interface:wealth_evaluator";
    public static final String INTERFACE_WORLD_MAP = "interface:world_map";
    public static final String INTERFACE_ZOMBIE_SPLAT_1 = "interface:zombie_splat_1";
    public static final String INTERFACE_ZOMBIE_SPLAT_2 = "interface:zombie_splat_2";
    public static final String INTERFACE_ZOMBIE_SPLAT_3 = "interface:zombie_splat_3";
    public static final String OTHER_ID1B0CB89 = "other:id1b0cb89";
    public static final String OTHER_ID1N9KOSU = "other:id1n9kosu";
    public static final String OTHER_ID1V05S02 = "other:id1v05s02";
    public static final String OTHER_NECROMANCY_HIT_2 = "other:necromancy_hit_2";
    public static final String OTHER_NECROMANCY_HIT_3 = "other:necromancy_hit_3";
    public static final String PRAYER_BESERKER = "prayer:beserker";
    public static final String PRAYER_DEFLECT_MAGIC = "prayer:deflect_magic";
    public static final String PRAYER_DEFLECT_MELEE = "prayer:deflect_melee";
    public static final String PRAYER_DEFLECT_NECROMANCY = "prayer:deflect_necromancy";
    public static final String PRAYER_DEFLECT_RANGE = "prayer:deflect_range";
    public static final String PRAYER_DEFLECT_SUMMONING = "prayer:deflect_summoning";
    public static final String PRAYER_ID1I9GMVW = "prayer:id1i9gmvw";
    public static final String PRAYER_LEECH_DEFENCE = "prayer:leech_defence";
    public static final String PRAYER_LEECH_MAGIC_ATTACK = "prayer:leech_magic_attack";
    public static final String PRAYER_LEECH_MAGIC_STRENGTH = "prayer:leech_magic_strength";
    public static final String PRAYER_LEECH_MELEE_ATTACK = "prayer:leech_melee_attack";
    public static final String PRAYER_LEECH_MELEE_STRENGTH = "prayer:leech_melee_strength";
    public static final String PRAYER_LEECH_RANGED_ATTACK = "prayer:leech_ranged_attack";
    public static final String PRAYER_LEECH_RANGED_STRENGTH = "prayer:leech_ranged_strength";
    public static final String PRAYER_LEECH_RUN_ENERGY = "prayer:leech_run_energy";
    public static final String PRAYER_PROTECT_ITEM = "prayer:protect_item";
    public static final String PRAYER_QUICK_PRAYER_1 = "prayer:quick_prayer_1";
    public static final String PRAYER_QUICK_PRAYER_2 = "prayer:quick_prayer_2";
    public static final String PRAYER_SAP_ADRENALINE = "prayer:sap_adrenaline";
    public static final String PRAYER_SAP_DEFENCE = "prayer:sap_defence";
    public static final String PRAYER_SAP_MAGIC_ATTACK = "prayer:sap_magic_attack";
    public static final String PRAYER_SAP_MAGIC_STRENGTH = "prayer:sap_magic_strength";
    public static final String PRAYER_SAP_MELEE_ATTACK = "prayer:sap_melee_attack";
    public static final String PRAYER_SAP_MELEE_STRENGTH = "prayer:sap_melee_strength";
    public static final String PRAYER_SAP_NECROMANCY_ATTACK = "prayer:sap_necromancy_attack";
    public static final String PRAYER_SAP_NECROMANCY_STRENGTH = "prayer:sap_necromancy_strength";
    public static final String PRAYER_SAP_RANGED_ATTACK = "prayer:sap_ranged_attack";
    public static final String PRAYER_SAP_RANGED_STRENGTH = "prayer:sap_ranged_strength";
    public static final String PRAYER_SAP_STRENGTH = "prayer:sap_strength";
    public static final String PRAYER_SOUL_SPLIT = "prayer:soul_split";
    public static final String PRAYER_SOULSPLIT = "prayer:soulsplit";
    public static final String PRAYER_WRATH = "prayer:wrath";
    public static final String SKILL_AGILITY = "skill:agility";
    public static final String SKILL_ARCHAEOLOGY = "skill:archaeology";
    public static final String SKILL_ATTACK = "skill:attack";
    public static final String SKILL_CONSTITUTION = "skill:constitution";
    public static final String SKILL_CONSTRUCTION = "skill:construction";
    public static final String SKILL_COOKING = "skill:cooking";
    public static final String SKILL_CRAFTING = "skill:crafting";
    public static final String SKILL_DEFENCE = "skill:defence";
    public static final String SKILL_DIVINATION = "skill:divination";
    public static final String SKILL_DUNGEONEERING = "skill:dungeoneering";
    public static final String SKILL_FARMING = "skill:farming";
    public static final String SKILL_FIREMAKING = "skill:firemaking";
    public static final String SKILL_FISHING = "skill:fishing";
    public static final String SKILL_FLETCHING = "skill:fletching";
    public static final String SKILL_HERBLORE = "skill:herblore";
    public static final String SKILL_HUNTER = "skill:hunter";
    public static final String SKILL_ID1NKFV7E = "skill:id1nkfv7e";
    public static final String SKILL_INVENTION = "skill:invention";
    public static final String SKILL_MAGIC = "skill:magic";
    public static final String SKILL_MINING = "skill:mining";
    public static final String SKILL_NECROMANCY = "skill:necromancy";
    public static final String SKILL_PRAYER = "skill:prayer";
    public static final String SKILL_RANGED = "skill:ranged";
    public static final String SKILL_RUNECRAFTING = "skill:runecrafting";
    public static final String SKILL_SLAYER = "skill:slayer";
    public static final String SKILL_SMITHING = "skill:smithing";
    public static final String SKILL_STRENGTH = "skill:strength";
    public static final String SKILL_SUMMONING = "skill:summoning";
    public static final String SKILL_THIEVING = "skill:thieving";
    public static final String SKILL_WOODCUTTING = "skill:woodcutting";
    public static final String TELEPORT_ARDOUGNE_TELEPORT = "teleport:ardougne_teleport";
    public static final String TELEPORT_CAMELOT_TELEPORT = "teleport:camelot_teleport";
    public static final String TELEPORT_CATHERBY_TELEPORT = "teleport:catherby_teleport";
    public static final String TELEPORT_CITY_OF_UM_TELEPORT = "teleport:city_of_um_teleport";
    public static final String TELEPORT_CONJURE_PHANTOM_GUARDIAN = "teleport:conjure_phantom_guardian";
    public static final String TELEPORT_CONSTITUTION_ABILITIES = "teleport:constitution_abilities";
    public static final String TELEPORT_FALADOR_TELEPORT = "teleport:falador_teleport";
    public static final String TELEPORT_HOME_TELEPORT = "teleport:home_teleport";
    public static final String TELEPORT_HOUSE_TELEPORT = "teleport:house_teleport";
    public static final String TELEPORT_ID11Z3I2X = "teleport:id11z3i2x";
    public static final String TELEPORT_ID14D47KE = "teleport:id14d47ke";
    public static final String TELEPORT_ID1B0CB89 = "teleport:id1b0cb89";
    public static final String TELEPORT_ID1HZS2JC = "teleport:id1hzs2jc";
    public static final String TELEPORT_IDO07MZ7 = "teleport:ido07mz7";
    public static final String TELEPORT_IDY89O2A = "teleport:idy89o2a";
    public static final String TELEPORT_LESSER_BONE_SHEILD_DEACTIVATED = "teleport:lesser_bone_sheild_deactivated";
    public static final String TELEPORT_LUMBRIDGE_TELEPORT = "teleport:lumbridge_teleport";
    public static final String TELEPORT_SOUTH_FELDIP_HILLS_TELEPORT = "teleport:south_feldip_hills_teleport";
    public static final String TELEPORT_TAVERLY_TELEPORT = "teleport:taverly_teleport";
    public static final String TELEPORT_UNGAEL_TELEPORT = "teleport:ungael_teleport";
    public static final String TELEPORT_VARROCK_TELEPORT = "teleport:varrock_teleport";
    public static final String TELEPORT_WARS_RETREAT_TELEPORT = "teleport:wars_retreat_teleport";
    public static final String TELEPORT_WATCHTOWER_TELEPORT = "teleport:watchtower_teleport";

    public static final String[] SPRITE_NAMES = {
        "ability:ability_wait_7",
        "ability:anticipation",
        "ability:asphyxiate",
        "ability:attack_abilities",
        "ability:backhand",
        "ability:barge",
        "ability:barricade",
        "ability:bash",
        "ability:bloat",
        "ability:blood_siphon",
        "ability:bone_sheild_inactive",
        "ability:bone_shield_active",
        "ability:cast_familiar_special_ability",
        "ability:cease",
        "ability:combust",
        "ability:command_skeleton_warrior",
        "ability:command_vengeful_ghost",
        "ability:concetrated_blast",
        "ability:conjure_guardian_phantom",
        "ability:conjure_phantom_guardian",
        "ability:conjure_putrid_zombie",
        "ability:conjure_skeleton_warrior",
        "ability:conjure_undead_army",
        "ability:conjure_vengeful_ghost",
        "ability:corruption_blast",
        "ability:darkness",
        "ability:death_skulls",
        "ability:debilitate",
        "ability:deflect_summoning",
        "ability:devotion",
        "ability:dive",
        "ability:eat_food",
        "ability:escape",
        "ability:essence_of_finality",
        "ability:finger_of_death",
        "ability:flurry",
        "ability:freedom",
        "ability:galeshot",
        "ability:greater_bone_shield_active",
        "ability:health_bar_green",
        "ability:ice_asylum",
        "ability:ice_barrage",
        "ability:id11j5awr",
        "ability:id156qq6p",
        "ability:id1dfkyl4",
        "ability:id1g090o2",
        "ability:id1ngwn7r",
        "ability:id1nl6pa4",
        "ability:idabrv9t",
        "ability:idkgujt",
        "ability:idxaiinn",
        "ability:idzd075o",
        "ability:imbue:_shadows",
        "ability:immortality",
        "ability:incite",
        "ability:invoke_death",
        "ability:life_transfer",
        "ability:living_death",
        "ability:magic",
        "ability:magic:spin_flax",
        "ability:necromancy",
        "ability:necromancy_abilities",
        "ability:omnipower",
        "ability:overpower",
        "ability:preparation",
        "ability:provoke",
        "ability:punish",
        "ability:ranged",
        "ability:ranged_abilities",
        "ability:reflect",
        "ability:regenerate",
        "ability:rejuvenate",
        "ability:rend",
        "ability:revenge",
        "ability:sacrafice",
        "ability:sap_defence",
        "ability:sap_magic_strength",
        "ability:siphon",
        "ability:sonic_wave",
        "ability:soul_sap",
        "ability:special_attack",
        "ability:spectral_scythe",
        "ability:split_soul",
        "ability:surge",
        "ability:threads_of_fate",
        "ability:touch_of_death",
        "ability:transfigure",
        "ability:tsunami",
        "ability:volley_of_souls",
        "bar:adrenaline_bar",
        "bar:adrenaline_bar_background",
        "bar:adrenaline_bar_full_background",
        "bar:adrenaline_bar_overcharge",
        "bar:blue_background_bar",
        "bar:conjure_bar_background",
        "bar:green_bar",
        "bar:skilling_bar_beginning",
        "bar:skilling_bar_end",
        "bar:skilling_bar_middle",
        "bar:yellow_frontground_bar",
        "buff:bloat",
        "buff:bone_shield",
        "buff:buff_box",
        "buff:command_putrid_zombie",
        "buff:devotion",
        "buff:freedom",
        "buff:necrosis",
        "buff:putrid_zombie",
        "buff:residual_soul",
        "buff:skeleton_warrior",
        "buff:vengeful_ghost",
        "chat:id1a0b3gf",
        "chat:id1qbj1gl",
        "chat:idipydxw",
        "chatbox:all_chat",
        "chatbox:chat_cog",
        "chatbox:chat_filter",
        "chatbox:chatbox_cog",
        "chatbox:clan_chat",
        "chatbox:clan_chat_list",
        "chatbox:friends_chat",
        "chatbox:friends_chat_list",
        "chatbox:friends_list",
        "chatbox:group_chat",
        "chatbox:group_chat_list",
        "chatbox:guest_clan_chat",
        "chatbox:id1eh8qo7",
        "chatbox:id1f6hc4u",
        "chatbox:idbihu5w",
        "chatbox:idfbt6rn",
        "chatbox:ironman",
        "chatbox:news_icon",
        "chatbox:quick_chat",
        "enemy_debuff:bloat",
        "enemy_debuff:defense_modified",
        "familiar:orb",
        "id11nqeck",
        "id198mxhv",
        "id1h4ro9i",
        "id1iyqj6n",
        "id1kfzfdv",
        "id1xvg1t0",
        "id6sner1",
        "id7duesd",
        "idb4oo8y",
        "idl9ssjy",
        "idmvcm2u",
        "idpmgs62",
        "idrldwuj",
        "interface:ability_activation_timer",
        "interface:ability_wait_1",
        "interface:ability_wait_2",
        "interface:ability_wait_3",
        "interface:ability_wait_5",
        "interface:ability_wait_6",
        "interface:adrenaline_bar",
        "interface:all_combat",
        "interface:auto_retaliate_on",
        "interface:buff_bar_3d",
        "interface:calendar",
        "interface:coin_pouch",
        "interface:conjure_bar",
        "interface:conjure_bar_1",
        "interface:conjure_bar_2",
        "interface:conjure_hitsplat_end",
        "interface:conjure_splat_3",
        "interface:constitution_icon",
        "interface:currency_pouch",
        "interface:defence_abilties",
        "interface:disassemble",
        "interface:emotes",
        "interface:empty_bar_3d",
        "interface:empty_bar_other_3d",
        "interface:familiar_bar",
        "interface:familiar_options",
        "interface:filter",
        "interface:health_bar_green",
        "interface:health_loss_bar",
        "interface:hitpoints_bar",
        "interface:hitpoints_icon",
        "interface:id10rewjf",
        "interface:id11gpyox",
        "interface:id1230yal",
        "interface:id12ctfzy",
        "interface:id12x6o2f",
        "interface:id1308n00",
        "interface:id1321hi9",
        "interface:id13g1hd5",
        "interface:id13i9wb1",
        "interface:id14r9347",
        "interface:id158ne25",
        "interface:id15cz86a",
        "interface:id15hc6rt",
        "interface:id15ojnaq",
        "interface:id16vjyn0",
        "interface:id18a2ol1",
        "interface:id19yhjwt",
        "interface:id1alm7gb",
        "interface:id1bnek5q",
        "interface:id1ct714f",
        "interface:id1d0rovo",
        "interface:id1d18iil",
        "interface:id1d5pzsc",
        "interface:id1d9b31n",
        "interface:id1deh90w",
        "interface:id1deuwki",
        "interface:id1ei5a4p",
        "interface:id1f485x0",
        "interface:id1fepfx",
        "interface:id1g090o2",
        "interface:id1g3dazp",
        "interface:id1gfhrrs",
        "interface:id1gft0ze",
        "interface:id1gw501j",
        "interface:id1hepsz9",
        "interface:id1hfeh0m",
        "interface:id1hizopr",
        "interface:id1ht5uv9",
        "interface:id1husf0r",
        "interface:id1jgtsf6",
        "interface:id1jr0x5w",
        "interface:id1k1ptal",
        "interface:id1k5zsko",
        "interface:id1k9cuoo",
        "interface:id1k9i5lf",
        "interface:id1kb1jt7",
        "interface:id1l65xao",
        "interface:id1lbwriv",
        "interface:id1lctl0i",
        "interface:id1lviok2",
        "interface:id1mre2td",
        "interface:id1n009sa",
        "interface:id1nfygxu",
        "interface:id1nldb00",
        "interface:id1npmzhm",
        "interface:id1nx0r7r",
        "interface:id1o7kbf7",
        "interface:id1owhy7u",
        "interface:id1p66e6x",
        "interface:id1p6qmmr",
        "interface:id1qffsdz",
        "interface:id1qzbhiz",
        "interface:id1rsc57a",
        "interface:id1rtgtm",
        "interface:id1s0ybmw",
        "interface:id1seb3gp",
        "interface:id1ssw4gz",
        "interface:id1sy954c",
        "interface:id1t383sc",
        "interface:id1u40zwt",
        "interface:id1vcf9yq",
        "interface:id1w7msod",
        "interface:id1wpfhlh",
        "interface:id1wrj9f4",
        "interface:id1wrvpww",
        "interface:id1wtu07l",
        "interface:id1wy1b4g",
        "interface:id1ygqk80",
        "interface:id1ynprtt",
        "interface:id1yruf8n",
        "interface:id1yziv8a",
        "interface:id268yb4",
        "interface:id2sc66l",
        "interface:id3fmehd",
        "interface:id3imx4r",
        "interface:id4ea0rj",
        "interface:id58543",
        "interface:id5ot662",
        "interface:id5p8w63",
        "interface:id5u11g9",
        "interface:id66wxyu",
        "interface:id6u306f",
        "interface:id70zj8q",
        "interface:id74imw0",
        "interface:id7jwuw1",
        "interface:id7oice2",
        "interface:id88r93r",
        "interface:id91a89k",
        "interface:id96s93b",
        "interface:idbqtgup",
        "interface:idc0t1e7",
        "interface:iddlf03x",
        "interface:ide4pume",
        "interface:ideb9uzz",
        "interface:ideeqz3v",
        "interface:idev9lhl",
        "interface:idf2jga3",
        "interface:idgnrktp",
        "interface:idh79i3k",
        "interface:idhidnf5",
        "interface:idhq4g5x",
        "interface:idibkc63",
        "interface:idifkfb8",
        "interface:idii9g52",
        "interface:idjs2m1e",
        "interface:idl9sh9x",
        "interface:idlm413k",
        "interface:idlmd6je",
        "interface:idlqw7nf",
        "interface:idlrxuup",
        "interface:idlzj8xz",
        "interface:idn6bco1",
        "interface:idn9p8q3",
        "interface:idnqlji5",
        "interface:idnz172",
        "interface:ido07mz7",
        "interface:ido4havu",
        "interface:idoehp0r",
        "interface:idowucm4",
        "interface:idp2ix07",
        "interface:idp6b4uc",
        "interface:idptxih7",
        "interface:idpxs1l1",
        "interface:idq2wag",
        "interface:idr3imen",
        "interface:idssmwt8",
        "interface:idt52ll5",
        "interface:idt594gj",
        "interface:idtkh2m7",
        "interface:idtpzvfk",
        "interface:idttrsj3",
        "interface:idu2uc0l",
        "interface:iduh1hr",
        "interface:iduu2zrs",
        "interface:iduvnchk",
        "interface:idvo4d7r",
        "interface:idw73jm1",
        "interface:idwerv2i",
        "interface:idwo0atg",
        "interface:idwq8bn3",
        "interface:idxc84nm",
        "interface:idxd3ycm",
        "interface:idyucoyi",
        "interface:idzd075o",
        "interface:idzli5lz",
        "interface:invention_materials",
        "interface:invoke_death",
        "interface:lock_inventory",
        "interface:magic",
        "interface:magic_abilities",
        "interface:magic_teleport_spells",
        "interface:melee_abilities",
        "interface:necromancy_abilities",
        "interface:necromancy_conjure_hit_1",
        "interface:necromancy_conjure_hit_2",
        "interface:necromancy_conjure_hitsplat_beginning",
        "interface:necromancy_hit_1",
        "interface:necromancy_incantations",
        "interface:prayer_bar",
        "interface:prayer_off",
        "interface:prayers_tab",
        "interface:quest_filter",
        "interface:quest_icon_1",
        "interface:quest_icon_2",
        "interface:quick_prayer",
        "interface:quick_prayer_4",
        "interface:ranged_abilities",
        "interface:residual_souls_empty",
        "interface:residual_souls_full",
        "interface:run_energy_on",
        "interface:slayer_icon",
        "interface:soul_sap",
        "interface:stun_immunity",
        "interface:total_xp",
        "interface:wealth_evaluator",
        "interface:world_map",
        "interface:zombie_splat_1",
        "interface:zombie_splat_2",
        "interface:zombie_splat_3",
        "other:id1b0cb89",
        "other:id1n9kosu",
        "other:id1v05s02",
        "other:necromancy_hit_2",
        "other:necromancy_hit_3",
        "prayer:beserker",
        "prayer:deflect_magic",
        "prayer:deflect_melee",
        "prayer:deflect_necromancy",
        "prayer:deflect_range",
        "prayer:deflect_summoning",
        "prayer:id1i9gmvw",
        "prayer:leech_defence",
        "prayer:leech_magic_attack",
        "prayer:leech_magic_strength",
        "prayer:leech_melee_attack",
        "prayer:leech_melee_strength",
        "prayer:leech_ranged_attack",
        "prayer:leech_ranged_strength",
        "prayer:leech_run_energy",
        "prayer:protect_item",
        "prayer:quick_prayer_1",
        "prayer:quick_prayer_2",
        "prayer:sap_adrenaline",
        "prayer:sap_defence",
        "prayer:sap_magic_attack",
        "prayer:sap_magic_strength",
        "prayer:sap_melee_attack",
        "prayer:sap_melee_strength",
        "prayer:sap_necromancy_attack",
        "prayer:sap_necromancy_strength",
        "prayer:sap_ranged_attack",
        "prayer:sap_ranged_strength",
        "prayer:sap_strength",
        "prayer:soul_split",
        "prayer:soulsplit",
        "prayer:wrath",
        "skill:agility",
        "skill:archaeology",
        "skill:attack",
        "skill:constitution",
        "skill:construction",
        "skill:cooking",
        "skill:crafting",
        "skill:defence",
        "skill:divination",
        "skill:dungeoneering",
        "skill:farming",
        "skill:firemaking",
        "skill:fishing",
        "skill:fletching",
        "skill:herblore",
        "skill:hunter",
        "skill:id1nkfv7e",
        "skill:invention",
        "skill:magic",
        "skill:mining",
        "skill:necromancy",
        "skill:prayer",
        "skill:ranged",
        "skill:runecrafting",
        "skill:slayer",
        "skill:smithing",
        "skill:strength",
        "skill:summoning",
        "skill:thieving",
        "skill:woodcutting",
        "teleport:ardougne_teleport",
        "teleport:camelot_teleport",
        "teleport:catherby_teleport",
        "teleport:city_of_um_teleport",
        "teleport:conjure_phantom_guardian",
        "teleport:constitution_abilities",
        "teleport:falador_teleport",
        "teleport:home_teleport",
        "teleport:house_teleport",
        "teleport:id11z3i2x",
        "teleport:id14d47ke",
        "teleport:id1b0cb89",
        "teleport:id1hzs2jc",
        "teleport:ido07mz7",
        "teleport:idy89o2a",
        "teleport:lesser_bone_sheild_deactivated",
        "teleport:lumbridge_teleport",
        "teleport:south_feldip_hills_teleport",
        "teleport:taverly_teleport",
        "teleport:ungael_teleport",
        "teleport:varrock_teleport",
        "teleport:wars_retreat_teleport",
        "teleport:watchtower_teleport",
    };
}
